# Generated by Django 2.2.6 on 2019-10-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
